#!/bin/bash                                                                                          
Tmp=/tmp/$$                                                                                              
trap 'exit 0' INT HUP QUIT TERM ALRM USR1                                                                
trap 'rm -f "$Tmp"' EXIT                                                                         
rm -f "$Tmp"  >/dev/null 2>&1     
opentable() {
    echo "<table valign='top'><tr valign='top'>"
}
closetable() {
    echo "</tr></table>"
    echo ""
}

# Generate the Markdown
put() {
    find . -type f | grep "$1" | sort | gawk -v sec="$1" '
    BEGIN {
       print "<td valign='top'>"
       print "NEWLINEHERE" 
       print "## " sec
       u = "https://raw.githubusercontent.com/archernar/scripts/main"
    }
    {
        sz = $0
        sub(/[.]/,"",sz)
        n=split(sz, A, "/")
        print "- [" A[n] "]"  "(" u sz ")"
    }
    END {
       print "</td>"
    }
    '
}

echo "" > README.md
opentable >> README.md
put "flashcards" >> README.md
put "oneliners" >> README.md
put "awk" >> README.md
put "bash" >> README.md
closetable >> README.md

echo "" >> README.md

opentable >> README.md
put "vimscript" >> README.md
put "java" >> README.md
put "css" >> README.md
put "adlist" >> README.md
closetable >> README.md

echo "" > $Tmp
echo "<!DOCTYPE html>" >> $Tmp
echo "<html lang='en'>" >> $Tmp
echo "" >> $Tmp
echo "<head>" >> $Tmp
echo "<link rel='stylesheet' href='simple.css'>" >> $Tmp
echo "<title>Links</title>" >> $Tmp
echo "</head>" >> $Tmp
echo "<body>" >> $Tmp
markdown README.md  >> $Tmp
echo "</body>" >> $Tmp
echo "</html>" >> $Tmp
cat $Tmp | sed 's/^[<].*$//' > README.html; cp README.html $Tmp;
cat $Tmp | sed 's/^$//' > README.html;      cp README.html $Tmp;
cat $Tmp | sed 's/^NEWLINEHERE//' > README.html;  cp README.html $Tmp;

cp README.md $Tmp
cat $Tmp | sed 's/^NEWLINEHERE//' > README.md
#-------------------------------------------------------------------------------------
git add README.md
git add README.html
git add pushit
git commit -m "Update"
git push -u origin main
REPO=scripts
#rm -rf $HOME/.vim/bundle/$REPO
#vim  -c ":PluginInstall! $REPO" -c ":qa!"
#-------------------------------------------------------------------------------------

