#!/bin/bash                                                                                          
Tmp=/tmp/$$                                                                                              
trap 'exit 0' INT HUP QUIT TERM ALRM USR1                                                                
trap 'rm -f "$Tmp"' EXIT                                                                         
rm -f "$Tmp"  >/dev/null 2>&1                                                                            

ls | sort >  README.md
git add README.md


#-------------------------------------------------------------------------------------
git commit -m "Update"
git push -u origin main
REPO=scripts
#rm -rf $HOME/.vim/bundle/$REPO
#vim  -c ":PluginInstall! $REPO" -c ":qa!"
#-------------------------------------------------------------------------------------

