#!/usr/bin/bash
Tmp=/tmp/$$

#   -h,  --help               Display this help and exit
#   -f,  --list-frames        Display all possible frames for id3v2
#   -L,  --list-genres        Lists all id3v1 genres
#   -v,  --version            Display version information and exit
#   -l,  --list               Lists the tag(s) on the file(s)
#   -R,  --list-rfc822        Lists using an rfc822-style format for output
#   -d,  --delete-v2          Deletes id3v2 tags
#   -s,  --delete-v1          Deletes id3v1 tags
#   -D,  --delete-all         Deletes both id3v1 and id3v2 tags
#   -C,  --convert            Converts id3v1 tag to id3v2
#   -1,  --id3v1-only         Writes only id3v1 tag
#   -2,  --id3v2-only         Writes only id3v2 tag
#   -r,  --remove-frame "FRAMEID"   Removes the specified id3v2 frame
#   -a,  --artist       "ARTIST"    Set the artist information
#   -A,  --album        "ALBUM"     Set the album title information
#   -t,  --song         "SONG"      Set the song title information
#   -c,  --comment      "DESCRIPTION":"COMMENT":"LANGUAGE"  
#                             Set the comment information (both
#                             description and language optional)
#   -g,  --genre   num        Set the genre number
#   -y,  --year    num        Set the year
#   -T,  --track   num/num    Set the track number/(optional) total tracks
#
LIST=""
WRITEIT="yes"
NORMALIZE=""
RENAME=""
          while getopts "t" arg
          do
              case $arg in
                  t) WRITEIT=""
                     ;;
              esac
          done
          shift $(($OPTIND - 1))



rm -rf ./taggerdo

TOTAL=0
for filename in *.mp3; do
    let TOTAL=TOTAL+1
done

rm -f  ./taggerdo
COUNTER=0

ls *.mp3 > $Tmp
ls *.mp3 > zed
cat $Tmp | while read -r filename; do
#        for filename in *.mp3; do
            if [ "$2" = "" ]; then
                NAME=`echo "$filename" | sed "s/$1//g"`
            else
                NAME=`echo "$filename" | sed "s/$1/$2/g"`
            fi
            NAME=`echo "$NAME"     | sed "s/\[.*\]//g"`
            NAME=`echo "$NAME"     | sed "s/^[&]//g"`
            NAME=`echo "$NAME"     | sed "s/[']//g"`
            NAME=`echo "$NAME" | sed "s/^ //"`
            NAME=`echo "$NAME" | sed "s/^ //"`
            NAME=`echo "$NAME" | sed "s/^ //"`
            NAME=`echo "$NAME" | sed "s/  / /"`
            NAME=`echo "$NAME" | sed "s/  / /"`
            NAME=`echo "$NAME" | sed "s/  / /"`
            NAMEMP3="$NAME"
                if [ "$filename" != "$NAMEMP3" ]; then
                    CMD="mv "
                    CMD=$CMD"\""
                    CMD=$CMD$filename
                    CMD=$CMD"\""
                    CMD=$CMD" "
                    CMD=$CMD"\""
                    CMD=$CMD$NAMEMP3
                    CMD=$CMD"\""
                    echo "$CMD"
                    echo "$CMD" > ./taggerdo
                    chmod 777  ./taggerdo
                    if [ "$WRITEIT" = "yes" ]; then
                       ./taggerdo
                   else
                       cat ./taggerdo
                    fi
                fi
#done
done
rm -f ./taggerdo
rm -f fed
rm -f zed
