#!/usr/bin/bash
Tmp="/tmp/$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm -f "$Tmp" >/dev/null 2>&1

FN="$1"
HN="$HOME/HJ/$1.html"


cat <<EOF > "$Tmp"
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="Java Code Example">
<meta name="keywords" content="Java, Tutorial, Basics, beginners">
<title>Java Programming Example</title>

<link rel="stylesheet" href="http://www.happyahab.com/pri.css">

</head>
<body>
<div id="wrap-outer">
        <div id="wrap-inner">
            <div id="content-main">
                <h3>TITLE</h3>
<pre><code class="language-java line-numbers">
EOF

cat "$FN" >> "$Tmp"

cat <<EOF >> "$Tmp"
</code></pre>
            </div>
        </div>
    </div>
</div>
<script src="http://www.happyahab.com/pri.js"></script>

</body>
</html>

EOF


cat $Tmp  | gawk -v rep="$1" '{sz=$0;sub(/^[.][/]/,"",rep);sub(/TITLE/,rep, sz);print sz;}' > "$HN"


